/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.js.script.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.remote.js.script.model.RemoteJsScriptEntry;
import com.liferay.remote.js.script.service.RemoteJsScriptEntryLocalService;
import com.liferay.remote.js.script.service.RemoteJsScriptEntryLocalServiceUtil;
import com.liferay.remote.js.script.service.persistence.RemoteJsScriptEntryPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the remote js script entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.remote.js.script.service.impl.RemoteJsScriptEntryLocalServiceImpl}.
 * </p>
 *
 * @author Bryce Osterhaus
 * @see com.liferay.remote.js.script.service.impl.RemoteJsScriptEntryLocalServiceImpl
 * @generated
 */
public abstract class RemoteJsScriptEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, RemoteJsScriptEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RemoteJsScriptEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>RemoteJsScriptEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the remote js script entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RemoteJsScriptEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param remoteJsScriptEntry the remote js script entry
	 * @return the remote js script entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RemoteJsScriptEntry addRemoteJsScriptEntry(RemoteJsScriptEntry remoteJsScriptEntry) {
		remoteJsScriptEntry.setNew(true);

		return remoteJsScriptEntryPersistence.update(remoteJsScriptEntry);
	}

	/**
	 * Creates a new remote js script entry with the primary key. Does not add the remote js script entry to the database.
	 *
	 * @param remoteJsScriptEntryId the primary key for the new remote js script entry
	 * @return the new remote js script entry
	 */
	@Override
	@Transactional(enabled = false)
	public RemoteJsScriptEntry createRemoteJsScriptEntry(long remoteJsScriptEntryId) {
		return remoteJsScriptEntryPersistence.create(remoteJsScriptEntryId);
	}

	/**
	 * Deletes the remote js script entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RemoteJsScriptEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param remoteJsScriptEntryId the primary key of the remote js script entry
	 * @return the remote js script entry that was removed
	 * @throws PortalException if a remote js script entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RemoteJsScriptEntry deleteRemoteJsScriptEntry(long remoteJsScriptEntryId)
		throws PortalException {

		return remoteJsScriptEntryPersistence.remove(remoteJsScriptEntryId);
	}

	/**
	 * Deletes the remote js script entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RemoteJsScriptEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param remoteJsScriptEntry the remote js script entry
	 * @return the remote js script entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RemoteJsScriptEntry deleteRemoteJsScriptEntry(RemoteJsScriptEntry remoteJsScriptEntry) {
		return remoteJsScriptEntryPersistence.remove(remoteJsScriptEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return remoteJsScriptEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RemoteJsScriptEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return remoteJsScriptEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.remote.js.script.model.impl.RemoteJsScriptEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return remoteJsScriptEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.remote.js.script.model.impl.RemoteJsScriptEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return remoteJsScriptEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return remoteJsScriptEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return remoteJsScriptEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RemoteJsScriptEntry fetchRemoteJsScriptEntry(long remoteJsScriptEntryId) {
		return remoteJsScriptEntryPersistence.fetchByPrimaryKey(remoteJsScriptEntryId);
	}

	/**
	 * Returns the remote js script entry with the matching UUID and company.
	 *
	 * @param uuid the remote js script entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching remote js script entry, or <code>null</code> if a matching remote js script entry could not be found
	 */
	@Override
	public RemoteJsScriptEntry fetchRemoteJsScriptEntryByUuidAndCompanyId(
		String uuid, long companyId) {

		return remoteJsScriptEntryPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the remote js script entry with the primary key.
	 *
	 * @param remoteJsScriptEntryId the primary key of the remote js script entry
	 * @return the remote js script entry
	 * @throws PortalException if a remote js script entry with the primary key could not be found
	 */
	@Override
	public RemoteJsScriptEntry getRemoteJsScriptEntry(long remoteJsScriptEntryId)
		throws PortalException {

		return remoteJsScriptEntryPersistence.findByPrimaryKey(remoteJsScriptEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(remoteJsScriptEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RemoteJsScriptEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("remoteJsScriptEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			remoteJsScriptEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RemoteJsScriptEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"remoteJsScriptEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(remoteJsScriptEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RemoteJsScriptEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("remoteJsScriptEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<RemoteJsScriptEntry>() {

				@Override
				public void performAction(RemoteJsScriptEntry remoteJsScriptEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, remoteJsScriptEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(RemoteJsScriptEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return remoteJsScriptEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return remoteJsScriptEntryLocalService.deleteRemoteJsScriptEntry(
			(RemoteJsScriptEntry)persistedModel);
	}

	@Override
	public BasePersistence<RemoteJsScriptEntry> getBasePersistence() {
		return remoteJsScriptEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return remoteJsScriptEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the remote js script entry with the matching UUID and company.
	 *
	 * @param uuid the remote js script entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching remote js script entry
	 * @throws PortalException if a matching remote js script entry could not be found
	 */
	@Override
	public RemoteJsScriptEntry getRemoteJsScriptEntryByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return remoteJsScriptEntryPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the remote js script entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.remote.js.script.model.impl.RemoteJsScriptEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of remote js script entries
	 * @param end the upper bound of the range of remote js script entries (not inclusive)
	 * @return the range of remote js script entries
	 */
	@Override
	public List<RemoteJsScriptEntry> getRemoteJsScriptEntries(int start, int end) {
		return remoteJsScriptEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of remote js script entries.
	 *
	 * @return the number of remote js script entries
	 */
	@Override
	public int getRemoteJsScriptEntriesCount() {
		return remoteJsScriptEntryPersistence.countAll();
	}

	/**
	 * Updates the remote js script entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RemoteJsScriptEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param remoteJsScriptEntry the remote js script entry
	 * @return the remote js script entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RemoteJsScriptEntry updateRemoteJsScriptEntry(RemoteJsScriptEntry remoteJsScriptEntry) {
		return remoteJsScriptEntryPersistence.update(remoteJsScriptEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RemoteJsScriptEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		remoteJsScriptEntryLocalService = (RemoteJsScriptEntryLocalService)aopProxy;

		_setLocalServiceUtilService(remoteJsScriptEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RemoteJsScriptEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RemoteJsScriptEntry.class;
	}

	protected String getModelClassName() {
		return RemoteJsScriptEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = remoteJsScriptEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		RemoteJsScriptEntryLocalService remoteJsScriptEntryLocalService) {

		try {
			Field field = RemoteJsScriptEntryLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, remoteJsScriptEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected RemoteJsScriptEntryLocalService remoteJsScriptEntryLocalService;

	@Reference
	protected RemoteJsScriptEntryPersistence remoteJsScriptEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}