import com.liferay.gradle.plugins.node.task.PublishNodeModuleTask
import com.liferay.gradle.util.FileUtil
import com.liferay.gradle.util.copy.ReplaceLeadingPathAction

task publishNodeModule(type: PublishNodeModuleTask)

File commonCssDestinationDir = file("tmp/META-INF/resources")

clean {
	delete "tmp"
}

publishNodeModule {
	dependsOn jar
	workingDir = "src/main/resources/META-INF/resources"
}

updateFileVersions {
	File gradlePluginsDir = new File("../../../../sdk/gradle-plugins")

	if (gradlePluginsDir.exists()) {
		match(/com\.liferay\.frontend\.css\.common=(\d.+)/, new File(gradlePluginsDir, "src/main/resources/com/liferay/gradle/plugins/dependencies/portal-tools.properties"))
	}
}